"use client";
import { FormEvent, useState } from "react";
type Check={label:string;status:"good"|"watch"|"risk";detail:string};
type Report={url:string;host:string;score:number;grade:string;generatedAt:string;location:{country:string;city:string;provider:string;ip:string};summary:string;checks:Check[];recommendations:string[];technologies:string[]};
const countries=["Australia","Singapore","Germany","United Kingdom","United States","India","Indonesia","New Zealand"];

export function ScanTool(){
 const[url,setUrl]=useState("");const[market,setMarket]=useState("Australia");const[report,setReport]=useState<Report|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError("");setReport(null);setLoading(true);try{const response=await fetch("/api/scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url,market})});const data=await response.json();if(!response.ok)throw new Error(data.error||"The scan could not be completed.");setReport(data)}catch(err){setError(err instanceof Error?err.message:"The scan could not be completed.")}finally{setLoading(false)}}
 return <main><header className="site-header"><a href="https://www.rackcorp.com/" target="_blank" rel="noreferrer" className="brand"><img src="/rackcorp-logo.png" alt="RackCorp"/></a><div className="header-tag"><span className="live-dot"/>Public infrastructure intelligence</div></header>
 <section className="hero"><div className="hero-inner"><div className="eyebrow">Free infrastructure assessment</div><h1>Is your website ready for<br/><span>sovereign, resilient growth?</span></h1><p>Run a fast external scan of your hosting location, security headers, resilience signals and data-sovereignty posture.</p><form onSubmit={submit} className="scan-form"><label><span>Website to assess</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="example.com" inputMode="url" required aria-label="Website URL"/></label><label><span>Primary market</span><select value={market} onChange={e=>setMarket(e.target.value)}>{countries.map(c=><option key={c}>{c}</option>)}</select></label><button disabled={loading}>{loading?<><i className="spinner"/>Scanning infrastructure…</>:<>Run free scan <b>→</b></>}</button></form><div className="trust-row"><span>✓ No login required</span><span>✓ Public data only</span><span>✓ Results in under a minute</span></div>{error&&<div className="error" role="alert">{error}</div>}</div><div className="signal-grid" aria-hidden="true"><div/><div/><div/><div/><div/><div/></div></section>
 {!report&&<section className="explainer"><div><small>01</small><h2>Hosting geography</h2><p>See where your public web infrastructure appears to be hosted and whether it aligns with your primary market.</p></div><div><small>02</small><h2>Security posture</h2><p>Check transport security, protective browser policies and common exposure indicators visible at the edge.</p></div><div><small>03</small><h2>Resilience signals</h2><p>Review CDN, DNS and platform signals that influence availability, latency and operational concentration risk.</p></div></section>}
 {report&&<section className="report" id="report"><div className="report-top"><div><div className="eyebrow dark">Infrastructure readiness report</div><h2>{report.host}</h2><p>Primary market: {market} · Scanned {new Date(report.generatedAt).toLocaleString()}</p></div><div className={`score score-${report.grade.toLowerCase()}`}><strong>{report.score}</strong><span>/ 100</span><em>Grade {report.grade}</em></div></div><div className="summary"><b>Assessment</b><p>{report.summary}</p></div><div className="facts"><div><span>Observed location</span><strong>{report.location.city||"Unknown"}{report.location.city&&report.location.country?", ":""}{report.location.country||"Not resolved"}</strong></div><div><span>Network / provider</span><strong>{report.location.provider||"Not disclosed"}</strong></div><div><span>Observed IP</span><strong className="mono">{report.location.ip||"Not resolved"}</strong></div></div><div className="checks"><h3>Readiness signals</h3>{report.checks.map((c,i)=><div className="check" key={i}><i className={c.status}>{c.status==="good"?"✓":c.status==="watch"?"!":"×"}</i><div><strong>{c.label}</strong><p>{c.detail}</p></div><span className={c.status}>{c.status}</span></div>)}</div><div className="rec-grid"><div><h3>Recommended next steps</h3><ol>{report.recommendations.map((r,i)=><li key={i}><span>{i+1}</span>{r}</li>)}</ol></div><aside><span className="aside-label">Detected web stack</span><div className="chips">{report.technologies.length?report.technologies.map(t=><span key={t}>{t}</span>):<span>Not disclosed</span>}</div><hr/><h3>Need a deeper review?</h3><p>RackCorp engineers can assess architecture, latency, resilience and sovereign hosting options across 35+ datacenters.</p><a href="https://www.rackcorp.com/contact-us/" target="_blank" rel="noreferrer">Talk to RackCorp <b>→</b></a></aside></div><div className="report-actions"><button onClick={()=>window.print()}>Save / print report</button><button className="secondary" onClick={()=>{setReport(null);setUrl("")}}>Scan another site</button></div><p className="method">This directional assessment uses public DNS, network and HTTP response data. It is not a penetration test, legal opinion or compliance certification.</p></section>}
 <footer><img src="/rackcorp-logo-footer.svg" alt="RackCorp"/><p>Secure Cloud Infrastructure you can trust.</p><span>Independent demonstration tool · Public data only</span></footer></main>
}
